# rustfmt.toml - stable channel compatible
# See: https://rust-lang.github.io/rustfmt/

# General settings
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Code organization
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true

# Formatting style
use_field_init_shorthand = true